/**
 * Claude Style — Anthropic warm-editorial skin for the dsh web GUI.
 *
 * Distilled from anthropic.com (see the ui-style-distiller report in
 * ~/anthropic-style-distill/distillation.md):
 *   - ivory canvas #FAF9F5 (light) / warm-black #141413 (dark)
 *   - one clay accent #D97757, deepening to #C6613F on hover (brand swatch)
 *   - serif display for headings, sans for UI chrome, mono for code
 *   - hairline warm borders, 8px radii, pill CTAs, editorial rhythm
 *
 * Hand-written bundle in the official __ModuleLoader__ format (no build
 * step): apply() sets the `data-dsh-claude-style` body attribute (the scope of the
 * whole stylesheet) and injects one <style> tag. Its effect disposer
 * retracts every write. Follows the native light/dark theme (dark tokens are
 * the base; the light palette applies when `data-ds-dark-theme` is absent).
 *
 * Presentation-only: no services injected, no cordis events, no model
 * requests.
 */
window.__ModuleLoader__.load({
  id: 'dsh-claude-style',
  factory: (require) => {
    'use strict'
    var module = { exports: {} }
    var exports = module.exports

    var STYLE_ID = 'dsh-claude-style-style'

    var SANS = "'Anthropic Sans Web Text','Noto Sans SC','Source Han Sans SC',-apple-system,BlinkMacSystemFont,'Segoe UI','PingFang SC','Hiragino Sans GB','Microsoft YaHei','Helvetica Neue',Helvetica,Arial,sans-serif"
    var SERIF = "'Anthropic Serif Web Text',Georgia,'Times New Roman','Noto Serif SC','Source Han Serif SC','Songti SC','SimSun',serif"
    var MONO = "'Anthropic Mono Variable',ui-monospace,'SF Mono','JetBrains Mono','Fira Code',Consolas,'Liberation Mono',Menlo,Courier,monospace"

    var CSS = [
      '/* ---------- design tokens: warm-black (dark) base ---------- */',
      'body[data-dsh-claude-style] {',
      '  --dsw-font-family: ' + SANS + ';',
      '  --dsw-font-serif: ' + SERIF + ';',
      '  --dsw-font-code: ' + MONO + ';',
      '  --dsw-font-markdown-h1-font-family: var(--dsw-font-serif);',
      '  --dsw-font-markdown-h2-font-family: var(--dsw-font-serif);',
      '  --dsw-font-markdown-h3-font-family: var(--dsw-font-serif);',
      '  --dsw-font-markdown-h4-font-family: var(--dsw-font-serif);',
      '  --dsw-font-markdown-base-font-family: var(--dsw-font-family);',
      '  --dsw-font-markdown-small-font-family: var(--dsw-font-family);',
      '  --dsw-font-markdown-table-font-family: var(--dsw-font-family);',
      '  --dsw-alias-bg-base: #141413;',
      '  --dsw-alias-bg-layer-1: #1c1b1a;',
      '  --dsw-alias-bg-layer-2: #242320;',
      '  --dsw-alias-bg-layer-3: #2e2c29;',
      '  --dsw-alias-bg-overlay: #242320;',
      '  --dsw-alias-border-l1: #242320;',
      '  --dsw-alias-border-l2: #2e2c29;',
      '  --dsw-alias-border-l3: #3a3833;',
      '  --dsw-alias-brand-primary: #d97757;',
      '  --dsw-alias-brand-text: #faf9f5;',
      '  --dsw-alias-button-elevated-fill: #242320;',
      '  --dsw-alias-button-floating-fill: #242320;',
      '  --dsw-alias-button-floating-hover: #2e2c29;',
      '  --dsw-alias-button-info-fill: #d97757;',
      '  --dsw-alias-button-info-hover: #e08a6d;',
      '  --dsw-alias-interactive-bg-active: rgba(217, 119, 87, 0.30);',
      '  --dsw-alias-interactive-bg-hover: rgba(255, 255, 255, 0.06);',
      '  --dsw-alias-interactive-bg-hover-solid: #2e2c29;',
      '  --dsw-alias-label-primary: #faf9f5;',
      '  --dsw-alias-label-primary-bluish: #faf9f5;',
      '  --dsw-alias-label-secondary: #b0aea5;',
      '  --dsw-alias-label-tertiary: #8f8d84;',
      '  --dsw-alias-label-caption: #6b6a65;',
      '  --dsw-alias-state-business-primary: #d97757;',
      '  --dsw-alias-state-business-tertiary: #3a2a22;',
      '  --dsw-shadow-lv2: 0 4px 16px rgba(0, 0, 0, 0.30), 0 1px 3px rgba(0, 0, 0, 0.14);',
      '  --dsw-specific-input-major: #0f0e0d;',
      '  --dsw-specific-selector: #2e2c29;',
      '  --dsw-specific-sidebar-fill: #141413;',
      '}',
      '',
      '/* ---------- typography: serif display + sans UI + mono code ---------- */',
      'body[data-dsh-claude-style] {',
      '  font-family: var(--dsw-font-family);',
      '  color: #faf9f5;',
      '  background-color: #141413;',
      '}',
      '',
      'body[data-dsh-claude-style] :is(h1, h2, h3, h4, [class*="headline"], [class*="title"]) {',
      '  font-family: var(--dsw-font-serif);',
      '  font-weight: 500;',
      '  letter-spacing: -0.01em;',
      '  line-height: 1.25;',
      '}',
      '',
      '/* hero / display headings lean a touch heavier + tighter (editorial) */',
      'body[data-dsh-claude-style] :is(h1, [class*="headline"]) {',
      '  font-weight: 600;',
      '  letter-spacing: -0.015em;',
      '}',
      '',
      'body[data-dsh-claude-style] :is(pre, code, kbd, samp, [class*="mono"], [class*="codeBlock"], [class*="CodeBlock"]) {',
      '  font-family: var(--dsw-font-code);',
      '}',
      '',
      '/* editorial captions: uppercase, tracked out */',
      'body[data-dsh-claude-style] :is([class*="caption"], [class*="sectionLabel"]) {',
      '  text-transform: uppercase;',
      '  letter-spacing: 0.08em;',
      '  font-size: 12px;',
      '  font-weight: 500;',
      '}',
      '',
      'body[data-dsh-claude-style] :is([class*="label"], [class*="Label"]) {',
      '  letter-spacing: 0.06em;',
      '}',
      '',
      '/* ---------- canvas + hairline structure ---------- */',
      'body[data-dsh-claude-style] :is([data-pane="sidebar"], [class*="sidebarCol"]) {',
      '  background: #141413;',
      '  border-right: 1px solid #242320;',
      '}',
      '',
      'body[data-dsh-claude-style] :is([data-pane="conversation"], [class*="centerCol"]) {',
      '  background: #141413;',
      '}',
      '',
      '/* ---------- clay accent: one emphasis color, disciplined ---------- */',
      'body[data-dsh-claude-style] a {',
      '  color: #e08a6d;',
      '}',
      '',
      'body[data-dsh-claude-style] a:hover {',
      '  color: #f0a488;',
      '}',
      '',
      'body[data-dsh-claude-style] button[class*="brand"] {',
      '  color: #d97757;',
      '}',
      '',
      '/* The baked-in wordmark "HARNESS" badge (a pill rect + its letter paths)',
      '   looks crowded next to the whale + wordmark. Hide the badge entirely so',
      '   the brand reads as a clean whale + wordmark on the clay pill. */',
      'body[data-dsh-claude-style] button[class*="brand"] rect[fill="currentColor"],',
      'body[data-dsh-claude-style] button[class*="brand"] path[fill*="label-primary-inverted"] {',
      '  display: none;',
      '}',
      '',
      '/* pill CTAs: send + new session + settings sidebar actions */',
      'body[data-dsh-claude-style] button[class*="newSession"],',
      'body[data-dsh-claude-style] button[class*="_brand"],',
      'body[data-dsh-claude-style] button[class*="_primary"],',
      'body[data-dsh-claude-style] [data-slot="sidebar.settings"] > :is(button, [role="button"]) {',
      '  border-radius: 9999px;',
      '  background: #d97757;',
      '  color: #ffffff;',
      '  font-weight: 500;',
      '}',
      '',
      'body[data-dsh-claude-style] button[class*="newSession"]:hover,',
      'body[data-dsh-claude-style] button[class*="_brand"]:hover,',
      'body[data-dsh-claude-style] button[class*="_primary"]:hover,',
      'body[data-dsh-claude-style] [data-slot="sidebar.settings"] > :is(button, [role="button"]):hover {',
      '  background: #e08a6d;',
      '}',
      '',
      '/* Brand logo chip: drop the loud clay pill so the whale + wordmark sit',
      '   on the canvas. Adaptive logo color: espresso on light, ivory on dark. */',
      'body[data-dsh-claude-style]:not([data-ds-dark-theme]) button[class*="brand"],',
      'body[data-dsh-claude-style][data-ds-dark-theme] button[class*="brand"] {',
      '  background: transparent !important;',
      '  border: none;',
      '}',
      '',
      'body[data-dsh-claude-style]:not([data-ds-dark-theme]) button[class*="brand"] {',
      '  color: #141413 !important;',
      '}',
      '',
      'body[data-dsh-claude-style][data-ds-dark-theme] button[class*="brand"] {',
      '  color: #faf9f5 !important;',
      '}',
      '',
      '/* badges: full pill */',
      'body[data-dsh-claude-style] :is([class*="badge"], [class*="Badge"], [class*="tag"], [class*="Tag"]) {',
      '  border-radius: 9999px;',
      '}',
      '',
      '/* ---------- editorial markdown ---------- */',
      'body[data-dsh-claude-style] blockquote {',
      '  font-family: var(--dsw-font-serif);',
      '  font-style: italic;',
      '  color: #b0aea5;',
      '  border-left: 2px solid #d97757;',
      '  background: rgba(217, 119, 87, 0.06);',
      '  border-radius: 0 8px 8px 0;',
      '  padding: 0.6em 1em;',
      '}',
      '',
      'body[data-dsh-claude-style] pre {',
      '  background: #1c1b1a;',
      '  border: 1px solid #242320;',
      '  border-radius: 8px;',
      '}',
      '',
      'body[data-dsh-claude-style] code:not(pre code) {',
      '  background: #2e2c29;',
      '  border-radius: 4px;',
      '  padding: 0.15em 0.4em;',
      '  font-size: 0.88em;',
      '}',
      '',
      'body[data-dsh-claude-style] hr {',
      '  border: none;',
      '  border-top: 1px solid rgba(20, 20, 19, 0.14);',
      '  margin: 1.6em 0;',
      '}',
      '',
      'body[data-dsh-claude-style] table {',
      '  border-collapse: collapse;',
      '  font-size: 0.92em;',
      '  width: 100%;',
      '}',
      '',
      'body[data-dsh-claude-style] table th {',
      '  background: rgba(250, 249, 245, 0.06);',
      '  font-weight: 600;',
      '  text-align: left;',
      '}',
      '',
      'body[data-dsh-claude-style] table td, body[data-dsh-claude-style] table th {',
      '  border: none;',
      '  border-bottom: 1px solid rgba(20, 20, 19, 0.12);',
      '  padding: 0.6em 0.85em !important;',
      '}',
      '',
      '/* tabs: subtle editorial weighting */',
      'body[data-dsh-claude-style] [role="tab"] {',
      '  letter-spacing: 0.02em;',
      '  font-weight: 500;',
      '}',
      '',
      '/* technical meta (model selector, triggers) read as mono labels */',
      'body[data-dsh-claude-style] [class*="triggerLabel"],',
      'body[data-dsh-claude-style] [class*="selectLabel"],',
      'body[data-dsh-claude-style] [class*="monoLabel"] {',
      '  font-family: var(--dsw-font-code);',
      '  font-size: 12px;',
      '  letter-spacing: 0;',
      '}',
      '',
      '/* ---------- chrome details ---------- */',
      'body[data-dsh-claude-style] * {',
      '  scrollbar-width: thin;',
      '  scrollbar-color: rgba(58, 56, 51, 0.9) transparent;',
      '}',
      '',
      'body[data-dsh-claude-style] ::-webkit-scrollbar {',
      '  width: 8px;',
      '  height: 8px;',
      '}',
      '',
      'body[data-dsh-claude-style] ::-webkit-scrollbar-track {',
      '  background: transparent;',
      '}',
      '',
      'body[data-dsh-claude-style] ::-webkit-scrollbar-thumb {',
      '  background: rgba(58, 56, 51, 0.9);',
      '  border-radius: 9999px;',
      '}',
      '',
      'body[data-dsh-claude-style] ::-webkit-scrollbar-thumb:hover {',
      '  background: rgba(107, 106, 101, 0.9);',
      '}',
      '',
      'body[data-dsh-claude-style] ::selection {',
      '  background: rgba(217, 119, 87, 0.30);',
      '  color: inherit;',
      '}',
      '',
      'body[data-dsh-claude-style] :is(button, input, textarea, select, [role="button"], [role="tab"], [role="treeitem"]) {',
      '  outline: none;',
      '}',
      '',
      'body[data-dsh-claude-style] :is(button, input, textarea, select, [role="button"], [role="tab"], [role="treeitem"]):focus-visible {',
      '  outline: 2px solid rgba(217, 119, 87, 0.75);',
      '  outline-offset: 1px;',
      '}',
      '',
      '',
      '/* ================= light variant: ivory editorial ================= */',
      'body[data-dsh-claude-style]:not([data-ds-dark-theme]) {',
      '  --dsw-alias-bg-base: #faf9f5;',
      '  --dsw-alias-bg-layer-1: #f5f3ee;',
      '  --dsw-alias-bg-layer-2: #f0eee6;',
      '  --dsw-alias-bg-layer-3: #e8e6dc;',
      '  --dsw-alias-bg-overlay: #ffffff;',
      '  --dsw-alias-border-l1: #e8e6dc;',
      '  --dsw-alias-border-l2: #dedcd2;',
      '  --dsw-alias-border-l3: #d0cdc1;',
      '  --dsw-alias-brand-primary: #d97757;',
      '  --dsw-alias-button-info-fill: #d97757;',
      '  --dsw-alias-button-info-hover: #c6613f;',
      '  --dsw-alias-button-floating-fill: #ffffff;',
      '  --dsw-alias-button-floating-hover: #ffffff;',
      '  --dsw-alias-label-primary: #141413;',
      '  --dsw-alias-label-primary-bluish: #141413;',
      '  --dsw-alias-label-secondary: #6e6a60;',
      '  --dsw-alias-label-tertiary: #8f8a7e;',
      '  --dsw-alias-label-caption: #a6a094;',
      '  --dsw-alias-state-business-primary: #d97757;',
      '  --dsw-alias-state-business-tertiary: #e9dfd2;',
      '  --dsw-specific-input-major: #ffffff;',
      '  --dsw-specific-selector: #f0eee6;',
      '  --dsw-specific-sidebar-fill: #faf9f5;',
      '  --dsw-shadow-lv2: 0 4px 18px rgba(20, 20, 19, 0.10), 0 1px 3px rgba(20, 20, 19, 0.05);',
      '}',
      '',
      'body[data-dsh-claude-style]:not([data-ds-dark-theme]) {',
      '  color: #141413;',
      '  background-color: #faf9f5;',
      '}',
      '',
      'body[data-dsh-claude-style]:not([data-ds-dark-theme]) :is([data-pane="sidebar"], [class*="sidebarCol"]) {',
      '  background: #faf9f5;',
      '  border-right: 1px solid #e8e6dc;',
      '}',
      '',
      'body[data-dsh-claude-style]:not([data-ds-dark-theme]) :is([data-pane="conversation"], [class*="centerCol"]) {',
      '  background: #faf9f5;',
      '}',
      '',
      'body[data-dsh-claude-style]:not([data-ds-dark-theme]) a {',
      '  color: #c6613f;',
      '}',
      '',
      'body[data-dsh-claude-style]:not([data-ds-dark-theme]) a:hover {',
      '  color: #a94f2f;',
      '}',
      '',
      'body[data-dsh-claude-style]:not([data-ds-dark-theme]) button[class*="newSession"],',
      'body[data-dsh-claude-style]:not([data-ds-dark-theme]) button[class*="_brand"],',
      'body[data-dsh-claude-style]:not([data-ds-dark-theme]) button[class*="_primary"],',
      'body[data-dsh-claude-style]:not([data-ds-dark-theme]) [data-slot="sidebar.settings"] > :is(button, [role="button"]) {',
      '  background: #d97757;',
      '  color: #ffffff;',
      '}',
      '',
      'body[data-dsh-claude-style]:not([data-ds-dark-theme]) button[class*="newSession"]:hover,',
      'body[data-dsh-claude-style]:not([data-ds-dark-theme]) button[class*="_brand"]:hover,',
      'body[data-dsh-claude-style]:not([data-ds-dark-theme]) button[class*="_primary"]:hover,',
      'body[data-dsh-claude-style]:not([data-ds-dark-theme]) [data-slot="sidebar.settings"] > :is(button, [role="button"]):hover {',
      '  background: #c6613f;',
      '}',
      '',
      'body[data-dsh-claude-style]:not([data-ds-dark-theme]) blockquote {',
      '  color: #6e6a60;',
      '  border-left-color: #c6613f;',
      '  background: rgba(198, 97, 63, 0.05);',
      '}',
      '',
      'body[data-dsh-claude-style]:not([data-ds-dark-theme]) pre {',
      '  background: #f5f3ee;',
      '  border-color: #e8e6dc;',
      '}',
      '',
      'body[data-dsh-claude-style]:not([data-ds-dark-theme]) code:not(pre code) {',
      '  background: #e8e6dc;',
      '}',
      '',
      'body[data-dsh-claude-style]:not([data-ds-dark-theme]) table th {',
      '  background: #f0eee6;',
      '}',
      '',
      'body[data-dsh-claude-style]:not([data-ds-dark-theme]) * {',
      '  scrollbar-color: rgba(208, 205, 193, 0.9) transparent;',
      '}',
      '',
      'body[data-dsh-claude-style]:not([data-ds-dark-theme]) ::-webkit-scrollbar-thumb {',
      '  background: rgba(208, 205, 193, 0.9);',
      '}',
      '',
      'body[data-dsh-claude-style]:not([data-ds-dark-theme]) ::-webkit-scrollbar-thumb:hover {',
      '  background: rgba(143, 138, 126, 0.8);',
      '}',
      '',
      'body[data-dsh-claude-style]:not([data-ds-dark-theme]) ::selection {',
      '  background: rgba(217, 119, 87, 0.22);',
      '}',
      '',
    ].join('\n')

    /**
     * Apply the Claude Style skin: body attribute + style tag.
     * All writes are retracted by the effect disposer on dispose.
     * @param ctx - owning context (the effect lifecycle owns retraction).
     */
    function apply(ctx) {
      var body = document.body
      body.setAttribute('data-dsh-claude-style', '')

      var style = document.createElement('style')
      style.id = STYLE_ID
      style.dataset.skinChrome = 'dsh-claude-style-style'
      style.textContent = CSS
      document.head.appendChild(style)

      ctx.effect(function () {
        return function () {
          body.removeAttribute('data-dsh-claude-style')
          var el = document.getElementById(STYLE_ID)
          if (el) el.remove()
        }
      }, 'ui-skin-claude-style: Claude Style chrome')
    }

    exports.apply = apply
    return module.exports
  },
})
